services:

  db:
    image: postgres:14.15-alpine3.21
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: database123
  app:
    image: my-node-app
    ports:
      - "13000:3000"

    